### ISSUE TITLE
.htaccess file mentioned in README missing

### ISSUE THREAD

**Issue by exploide** [westnordost/sc-statistics-service#1]
`README.md` says:

> Perform appropriate file protection measures if included .htaccess file is not used

I do not see such a `.htaccess` file. Don't know if you want to add one or remove that statement from `README.md`. In the latter case, protecting files should be handled differently.

Besides, and perhaps related:

I'm not that happy with

https://github.com/westnordost/sc-statistics-service/blob/85d3ad2f585123dc554923928df58f0f15951e35/delete_data_of_deleted_users.php#L22-L25

where you download a foreign file into your webroot. It has the `.txt` extension, which is good so far, `.php` would obviously be bad. However, having foreign content in your webroot is certainly not the best thing you can do. In theory a webserver could be misconfigured to interpret PHP code from `.txt` files.

So I propose blocking this explicity in `.htaccess` or better, download it into a [temporary directory](https://www.php.net/manual/de/function.sys-get-temp-dir.php) outside of the webroot.

**Comment by westnordost** [comment]
Right, good hint with the downloading into a directory that is accessible from web and thanks for the hint to the temp dir. I will fix that. 
.htaccess is still missing because I am yet to add the "index.php" to the repository.
