### ISSUE TITLE
Rate Limit request for new Changesets from the OSM API

### ISSUE THREAD

**Issue by Akasch** [westnordost/sc-statistics-service#5]
I would add a check for the last update in [classes/ChangesetsWalker.class.php Line 51](https://github.com/westnordost/sc-statistics-service/blob/master/classes/ChangesetsWalker.class.php#L51) that the last update for the user is at least some time ago. I think something between 30 seconds and an hour would be good.

This would require to also set the last_update timestamp in the changesetsWalkerStateDao on an update with no new Changesets in Line [58](https://github.com/westnordost/sc-statistics-service/blob/master/classes/ChangesetsWalker.class.php#L58) (maybe generally a good Idea to see then the last check was)

**Comment by westnordost** [comment]
Is this implementation what you had in mind?

**Comment by Akasch** [comment]
Yes, looks good.
